# Generated by Django 5.1.6 on 2025-03-06 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='collage_name',
            new_name='college_name',
        ),
    ]
