# Generated by Django 5.1.6 on 2025-03-06 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0002_rename_collage_name_college_college_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgmember',
            old_name='data_joined',
            new_name='date_joined',
        ),
    ]
